<a href="https://colab.research.google.com/github/yanzhang135/learning-python/blob/main/basic%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Basic Numpy Arrays

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1,2,3,4])

In [6]:
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
a[0], a[1]

(1, 2)

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[1:-1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

numpy array is very similar to python list

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

select the same elements with a numpy array which is much faster

In [13]:
b[[0, 2, -1]]

array([0., 1., 2.])

# Array Types

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [18]:
np.array([1,2,3,], dtype = np.float)

array([1., 2., 3.])

# Dimensions and shapes

In [19]:
A = np.array([ 
   [1,2,3],
   [4,5,6]           
])

In [20]:
A.shape

(2, 3)

In [21]:
A.ndim

2

In [22]:
A.size

6

In [25]:
B = np.array([
              [
               [12,11,10],
               [9,8,7],
              ],
              [
               [6,5,4],
               [3,2,1]
              ]
])

In [26]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [27]:
B.shape

(2, 2, 3)

In [28]:
B.ndim

3

In [29]:
B.size

12

# Indexing and slicing of matrices

In [30]:
# square matrix
A = np.array([
              [1,2,3], # 0
              [2,3,4], # 1
              [7,8,9] #2
])

In [31]:
A[1]

array([2, 3, 4])

In [32]:
A[1][0]

2

In [33]:
A[1,0] # alternative way to select that same element

2

In [34]:
A[0:2] # in this way slicing can be done easily

array([[1, 2, 3],
       [2, 3, 4]])

In [35]:
A[:, :2] # slicing just like an matrix

array([[1, 2],
       [2, 3],
       [7, 8]])

In [36]:
A

array([[1, 2, 3],
       [2, 3, 4],
       [7, 8, 9]])

In [37]:
A[2]

array([7, 8, 9])

In [41]:
A[1] = np.array([10,10,10])
A[2]=99
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary statistics

In [43]:
a = np.array([1,2,3,4])

In [44]:
a.sum()

10

In [45]:
a.mean()

2.5

In [50]:
a.std()

1.118033988749895

In [51]:
a.var()

1.25

In [52]:
A = np.array([
              [1,2,3], 
              [4,5,6],
              [7,8,9]
])

In [53]:
A.sum()

45

In [54]:
A.mean()

5.0

In [55]:
A.std()

2.581988897471611

In [56]:
A.sum(axis=0) # per col

array([12, 15, 18])

In [58]:
A.sum(axis=1)  # per row

array([ 6, 15, 24])

# Broadcasting and Vetorizing operations

In [59]:
a = np.arange(4)

In [60]:
a

array([0, 1, 2, 3])

In [61]:
a + 10. # aha like the recycling in R

array([10, 11, 12, 13])

In [62]:
a * 10

array([ 0, 10, 20, 30])

In [63]:
a # the operation created a new array and left a UNCHANGED!

array([0, 1, 2, 3])

In [64]:
a += 100 # this is CHANGING a!!!

In [65]:
a

array([100, 101, 102, 103])

In [66]:
a

array([100, 101, 102, 103])

In [67]:
l = [0, 1, 2, 3]

In [68]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [70]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [72]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [73]:
a + b

array([10, 11, 12, 13])

In [74]:
a * b # works extremely fast

array([ 0, 10, 20, 30])

# Boolean arrays
_(also called masks)_



In [75]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [76]:
a[[0, -1]]

array([0, 3])

In [77]:
a[[True, False, False, True]]

array([0, 3])

In [78]:
a >= 2

array([False, False,  True,  True])

In [79]:
a[a>=2] # like applying a "greater than **" filter

array([2, 3])

In [80]:
a[a > a.mean()]

array([2, 3])

In [81]:
a[~(a > a.mean())] # less or equal to 

array([0, 1])

In [82]:
a[(a == 0 | (a == 1))]

array([0, 1])

In [83]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

also works with matrix

In [84]:
A = np.random.randint(100, size = (3,3))

In [85]:
A

array([[29, 97, 68],
       [96, 40, 13],
       [32, 56, 81]])

In [86]:
A[np.array([
            [True, False, True],
            [False, True, False],
            [True, False, True]
])]

array([29, 68, 40, 32, 81])

In [87]:
A > 80

array([[False,  True, False],
       [ True, False, False],
       [False, False,  True]])

In [88]:
A[A > 30]

array([97, 68, 96, 40, 32, 56, 81])

# Linear Algebra

In [90]:
A = np.random.randint(100, size = (3,3))
A

array([[22, 43, 88],
       [33,  7, 10],
       [40, 40, 15]])

In [93]:
B = np.random.randint(50, size = (3,2))
B

array([[24, 28],
       [41, 22],
       [ 1, 41]])

In [94]:
A.dot(B) # matrix multiply

array([[2379, 5170],
       [1089, 1488],
       [2615, 2615]])

In [95]:
A @ B

array([[2379, 5170],
       [1089, 1488],
       [2615, 2615]])

In [96]:
B.T

array([[24, 41,  1],
       [28, 22, 41]])

In [97]:
B.T @ A

array([[1921, 1359, 2537],
       [2982, 2998, 3299]])

# Size of objects in Memory

## Int, floats

In [99]:
# An integer in Python is > 24bytes
import sys
sys.getsizeof(1)

28

In [ ]:
# Longs are even larger